import type { Mission } from "../missions/level001";

export const bi008: Mission = {
  id: "bi-ticket-008",
  world: "AstraMind Analytics",
  levelLabel: "Ticket BI-008 // Priority: Critical",
  npc: "VP OF ANALYTICS KRISHNA MEHTA",
  briefing: [
    "02:15 PM. Internal system. Priority: Critical.",
    "\"Module capstone — the full management report. Four levels: individual sales rows, product subtotals within each region, region subtotals, and a grand total. ORDER BY must group each level correctly. This is the query that goes in the BI dashboard template.\"",
  ],
  objective:
    "Build the full 4-level report: detail rows, product-within-region subtotals (quarter='ALL'), region subtotals (product_line='ALL'), and grand total, sorted so each level groups under its parent.",
  schemaLabel: "sales",
  seedSql: `
    CREATE TABLE sales (
      id INTEGER PRIMARY KEY, region TEXT, product_line TEXT,
      quarter TEXT, amount INTEGER
    );
    INSERT INTO sales (id, region, product_line, quarter, amount) VALUES
      (1,'East','Software','Q1',85000),(2,'East','Software','Q2',92000),
      (3,'East','Hardware','Q1',120000),(4,'East','Hardware','Q2',135000),
      (5,'East','Services','Q1',45000),(6,'East','Services','Q2',52000),
      (7,'North','Software','Q1',67000),(8,'North','Software','Q2',71000),
      (9,'North','Hardware','Q1',98000),(10,'North','Hardware','Q2',105000),
      (11,'North','Services','Q1',38000),(12,'North','Services','Q2',41000),
      (13,'South','Software','Q1',54000),(14,'South','Software','Q2',59000),
      (15,'South','Hardware','Q1',77000),(16,'South','Hardware','Q2',83000),
      (17,'South','Services','Q1',29000),(18,'South','Services','Q2',33000),
      (19,'West','Software','Q1',110000),(20,'West','Software','Q2',118000),
      (21,'West','Hardware','Q1',155000),(22,'West','Hardware','Q2',162000),
      (23,'West','Services','Q1',58000),(24,'West','Services','Q2',65000);
  `,
  schemaPreview: [{ table: "sales", columns: ["id","region","product_line","quarter","amount"] }],
  expectedColumns: ["region", "product_line", "quarter", "amount", "row_type"],
  expectedRows: [
    ["East", "Hardware", "Q1", 120000, "Detail"],
    ["East", "Hardware", "Q2", 135000, "Detail"],
    ["East", "Hardware", "ALL", 255000, "Product Subtotal"],
    ["East", "Services", "Q1", 45000, "Detail"],
    ["East", "Services", "Q2", 52000, "Detail"],
    ["East", "Services", "ALL", 97000, "Product Subtotal"],
    ["East", "Software", "Q1", 85000, "Detail"],
    ["East", "Software", "Q2", 92000, "Detail"],
    ["East", "Software", "ALL", 177000, "Product Subtotal"],
    ["East", "ALL", "ALL", 529000, "Region Subtotal"],
    ["North", "Hardware", "Q1", 98000, "Detail"],
    ["North", "Hardware", "Q2", 105000, "Detail"],
    ["North", "Hardware", "ALL", 203000, "Product Subtotal"],
    ["North", "Services", "Q1", 38000, "Detail"],
    ["North", "Services", "Q2", 41000, "Detail"],
    ["North", "Services", "ALL", 79000, "Product Subtotal"],
    ["North", "Software", "Q1", 67000, "Detail"],
    ["North", "Software", "Q2", 71000, "Detail"],
    ["North", "Software", "ALL", 138000, "Product Subtotal"],
    ["North", "ALL", "ALL", 420000, "Region Subtotal"],
    ["South", "Hardware", "Q1", 77000, "Detail"],
    ["South", "Hardware", "Q2", 83000, "Detail"],
    ["South", "Hardware", "ALL", 160000, "Product Subtotal"],
    ["South", "Services", "Q1", 29000, "Detail"],
    ["South", "Services", "Q2", 33000, "Detail"],
    ["South", "Services", "ALL", 62000, "Product Subtotal"],
    ["South", "Software", "Q1", 54000, "Detail"],
    ["South", "Software", "Q2", 59000, "Detail"],
    ["South", "Software", "ALL", 113000, "Product Subtotal"],
    ["South", "ALL", "ALL", 335000, "Region Subtotal"],
    ["West", "Hardware", "Q1", 155000, "Detail"],
    ["West", "Hardware", "Q2", 162000, "Detail"],
    ["West", "Hardware", "ALL", 317000, "Product Subtotal"],
    ["West", "Services", "Q1", 58000, "Detail"],
    ["West", "Services", "Q2", 65000, "Detail"],
    ["West", "Services", "ALL", 123000, "Product Subtotal"],
    ["West", "Software", "Q1", 110000, "Detail"],
    ["West", "Software", "Q2", 118000, "Detail"],
    ["West", "Software", "ALL", 228000, "Product Subtotal"],
    ["West", "ALL", "ALL", 668000, "Region Subtotal"],
    ["ALL", "ALL", "ALL", 1952000, "Grand Total"],
  ],
  requireRowOrder: true,
  hints: [
    "Four SELECT blocks in one UNION ALL — detail rows, product subtotals (GROUP BY region, product_line), region subtotals (GROUP BY region), grand total. Use 'ALL' as the placeholder for collapsed dimensions.",
    "ORDER BY 5 DESC, 1, 2, 3 — column 5 is row_type, which alphabetically sorts Detail first, Grand Total last, Product Subtotal and Region Subtotal in between.",
    "Try: SELECT region, product_line, quarter, amount, 'Detail' AS row_type FROM sales UNION ALL SELECT region, product_line, 'ALL', SUM(amount), 'Product Subtotal' FROM sales GROUP BY region, product_line UNION ALL SELECT region, 'ALL', 'ALL', SUM(amount), 'Region Subtotal' FROM sales GROUP BY region UNION ALL SELECT 'ALL','ALL','ALL', SUM(amount), 'Grand Total' FROM sales ORDER BY 5 DESC, 1, 2, 3;",
  ],
  xpAward: 300,
};
